
<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>
<?php if ($exist):?>
<!--new arrivals-->
<section class="midd_wrapper">
<article class="container">
	<div class="new_arrivals">
    <div class="row">
    	<aside class="col-md-4">
        	<div class="dealss">
            <h2><?php /* @escapeNotVerified */ echo $title; ?></h2>
            <h4>Deals of the week</h4>
            </div>
        </aside>

        <div class="col-md-8">
        <div class="deal_scroll">
	
                      <div id="owl-demo2" class="owl-carousel">
					   <?php foreach ($items as $_item): ?>
                        
                        <div class="item">
                            <div class="arrival_pro">
                                <div class="row">
								<!-- image -->
								<aside class="col-md-6 product_photo">
                                    <div class="photo_pro"><?php echo $block->getImage($_item, $image)->toHtml(); ?></div>
                                </aside>
								<!-- end image -->
								
								 <aside class="col-md-6">
                                    <div class="pro_dt">

                                        <div class="product_logo"><a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a></div>
                                        <h4><?php echo $block->getProductPriceHtml($_item, $type); ?> </h4>
                                       <!--
                                        <input name="" type="button" class="cart_btn" value="ADD TO CART"> -->

										
										
										  <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="cart_btn action tocart "
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="cart_btn action  "
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
										
                                       
                                    </div>
                                <?php endif; ?>
								
								
                                    </div>
                                    </aside>
									
									
                               
                            
                              
                            </div>
                        </div>
                        </div>
                    
                    <?php endforeach ?>
					
					
                      </div>

		</div>
        </div>

	</div>
	</div>
</article>
</section>
<!--new arrivals-->
<?php endif;?>

<!--
  <script>
    (function  () {
        require(["jquery","owlcarousel"],function($) {
            $(document).ready(function() {
                $("#owl-demo2").owlCarousel({
                        navigation : true,
						autoPlay: false, //Set AutoPlay to 3 seconds 
      slideSpeed : 800,
      paginationSpeed : 400,
	 
      singleItem : true

      // "singleItem:true" is a shortcut for:
      //  items : 1,
      // itemsDesktop : false,
      // itemsDesktopSmall : false,
      // itemsTablet: false,
      // itemsMobile : false
                });
            });
        });
    })();
    </script>
-->