<?php
if ($exist = ($this->getBestsellerProduct() && $this->getBestsellerProduct()->getPageSize())) {
$fet_prodcollection = $this->getBestsellerProduct();
$productcount = $this->getProductLimit();
$imagewidth = $this->getProductimagewidth();
$imageheight = $this->getProductimageheight();
 $mode = 'grid';
  $title = __('Bestseller Products');
 $type = 'widget-bestseller-grid';
 $image = 'bestseller_products_content_widget_grid';
}
?>
<?php if ($exist):?>
<article class="container">
        <!--best sellers-->
        <div class="products_items">
		<h2>Best Seller</h2>

        <div class="slider_wrap bestsllrss">

        <div id="owl-demo" class="owl-carousel">
		  <?php foreach ($fet_prodcollection as $item):     
    
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());

    ?>
                <div class="item">
                    <div class="product_list">
                    <div class="item_inn">
                    <section  class="gallery simplegallery">
			<?php 
                
            $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')
                        ->setImageFile($_product->getFile())
                        ->resize($imagewidth,$imageheight)
                        ->getUrl();
                        
			?>
                            
							
                    <div class="content">
                    <img src="<?php echo  $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
					<!--
                    <img src="images/product1-view1s.jpg" class="image_2" style="display:none" alt="" />
                    <img src="images/product1-view1ss.jpg" class="image_3" style="display:none" alt="" /> -->
                    </div>

                    <div class="thumbnail">
					
                    <div class="thumb"><a href="#" rel="1">
					<img src="<?php echo  $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" id="thumb_1"/></a></div>
					<!--
                    <div class="thumb"><a href="#" rel="2"><img src="images/product1-view1s.jpg" id="thumb_2" alt="" /></a></div>
                    <div class="thumb"><a href="#" rel="3"> <img src="images/product1-view1ss.jpg" id="thumb_3" alt="" /> </a></div> -->
                    </div>
        			</section>
                    </div>

                    <div class="item_dt">
                    <h3><?php echo $block->escapeHtml($_product->getName()) ?></h3>
                    <h4><?php echo $this->getProductPriceHtml($_product, $type); ?><!--<span></span>--></h4>
                   
                    
                    <div class="spec_btns">
					 <div class="product-item-actions">
                                       
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()): ?>
                                                    <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <button class="action tocart cart_btn"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                           
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId()]);
                                                        ?>
                                                        <button class="action tocart cart_btn "
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                       
                                       
                                    </div>
									
									
						
						<input name="" type="button" class="wish_btn" value="" title="Add To Wishlist">
					</div>
                    
                    </div>
					
					<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl($item) ?>" class="product-item-photo"><input name="" type="button" value="QUICK VIEW" class="view_btn"></a>
							
                   
                    </div>
                </div>
				<?php endforeach ?>
<!-- -->
            
              </div>


        </div>
        </div>
        <!--best sellers-->
</article>



<?php endif;?>

