<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>

<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>

	<article class="container">
	<div class="main_top">
        <div class="row">
        <aside class="col-md-5 left_top">
        	<div class="phone_ex"><h4>+1(000) 2345-6789</h4>
            <h6>7 Days a week from 9:00 am to 7:00 pm</h6></div>
			

    		<ul class="account_link">
    			<li><?php
    $objectManagerlogin = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManagerlogin->get('Magento\Customer\Model\Session');
    $baseurl = $objectManagerlogin->get('Magento\Store\Model\StoreManagerInterface')->getStore(0)->getBaseUrl();
?>
    <?php if($customerSession->isLoggedIn()) { ?>
   <a href="<?php echo $baseurl .'customer/account/logout'; ?>">Logout</a>
    <?php }else { ?>
	<!--
        <a  href="<?php echo $baseurl .'customer/account/login'; ?>" data-reveal-id="myModal_login" data-animation="fade" data-reveal-ajax="true" >Sign In</a>       -->
		        <a  href="<?php echo $baseurl .'customer/account/login'; ?>"  >Sign In</a>       
        <?php
    }
    ?></li>
      <li><a href="<?php echo $baseurl .'customer/account/create'; ?>">Register</a></li>
            </ul>
    	</aside>
		<!--popup-->
<div id="myModal_login" class="reveal-modal2">

<div class="sign_in">
<h3>Sign In</h3>
<iframe src="<?php echo $baseurl .'customer/account/login'; ?>"></iframe>
</div> 
			<a class="close-reveal-modal"></a>
		</div>



<!--popup-->

        <div class="col-md-2 logoarea">
		
		
<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>

<?php else: ?>
    <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
<?php endif ?>
        <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
<?php if ($block->isHomePage()):?>
   
<?php else:?>
    </a>
<?php endif?>


		</div>
    	<aside class="col-md-5">
        <div class=" right_top">
        <div class="lang_switch">

        <select id="basic" class="selectpicker show-tick form-control select_lang">
          <option>English</option>
          <option>Arabic</option>
        </select>


        </div> <!--		<a href="<?php echo $baseurl .'wishlist'; ?>">wishlist</a> -->
		<!-- wisth list link -->
		<!--
		<span data-bind="scope: 'wishlist'" class="link wishlist">
<a href="<?php echo $this->getUrl('wishlist') ?>"><div class="wshlist">
   <h6> <?php echo __('My Wishlist') ?>
    <span data-bind="text: wishlist().counter" class="counter qty"></span></h6>
	<img src='<?php echo $this->getViewFileUrl('images/arrow-bottom.png'); ?>' />
</div></a></span> -->

<a href="<?php echo $baseurl .'wishlist'; ?>"><div class="wshlist">
	    	<h6>Wishlist <span>( 0 )</span></h6>
	    	<img src="<?php echo $this->getViewFileUrl('images/arrow-bottom.png'); ?>" alt="">
	    	</div></a>

		<!-- cart -->
<?php  echo $this->getLayout()
          ->createBlock('Magento\Checkout\Block\Cart\Sidebar')
          ->setTemplate('Magento_Checkout::cart/minicart.phtml')
          ->toHtml(); ?>

      <?php echo $this->getChildHtml('topSearch') ?>

        <div class="list-box">
        <div class="top_aroww"><img src='<?php echo $this->getViewFileUrl('images/arrow-top.png'); ?>' ></div>
            <div class="select-result">

                	<div class="pro_listing">
                        <div class="pro-image"><img src='<?php echo $this->getViewFileUrl('images/product1-view1.jpg'); ?>' ></div>
                        <div class="pro_exdt">
                            <h3>MAKEUP FOREVER</h3>
                            <h4>120.00 KD</h4>
                            <h5>Qty : 1 pcs</h5>
                        </div>
                        <a href="#" class="close_btn"></a>
                    </div>

                    <div class="pro_listing">
                        <div class="pro-image"><img src='<?php echo $this->getViewFileUrl('images/product1-view4.jpg'); ?>' ></div>
                        <div class="pro_exdt">
                            <h3>GUERLAIN</h3>
                            <h4>140.00 KD</h4>
                            <h5>Qty : 1 pcs</h5>
                        </div>
                        <a href="#" class="close_btn"></a>
                    </div>

                    <div class="sub-total"><h2>Subtotals: <span>260.00 KD</span></h2></div>
                    <div class="chk-buttons">
                    <a href="#" class="chkout">CHECKOUT</a>
                    <a href="cart.html" class="viwcart">VIEW SHOPPING CART</a>
                    </div>
            </div>
        </div>





    	</div>
    	</aside>
        </div>
    </div>

    <!--nav-->
    <nav class="main_menu">

    <nav class="navbar navbar-default">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse js-navbar-collapse">
      <ul class="nav navbar-nav">

        			<li><a href="index.html">Home</a></li>
                    
                   <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle disabled" href="<?php echo $baseurl .'about'; ?>">About US <span class="glyphicon glyphicon-chevron-down pull-right caret-small"></span></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="service-staff.html">Staff</a></li>
            			<li><a href="csr.html">CSR</a></li>
                    </ul>
                	</li>
                    
                    


										<li class="dropdown mega-dropdown">
          <a href="shop-by-category.html">Categories
          <span class="glyphicon glyphicon-chevron-down pull-right caret-small"></span></a>

          <ul class="dropdown-menu mega-dropdown-menu megaMenu-1 row">
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Special Products</li>
                <div id="myCarousel1" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">

                    <div class="item active">
                      <a href="#"><img src="" class="img-responsive" alt="product 1">
					  <img src='<?php echo $this->getViewFileUrl('images/product1-view4.jpg'); ?>' >
					  </a>
                      <h4>Hair Colouring</h4>
                      <h5>30.00 KD <span>45.00 KD</span></h5>
                    </div>

                    <div class="item">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service5.jpg'); ?>' ></a>
                      <h4>Makeup</h4>
                      <h5>55.00 KD <span>70.00 KD</span></h5>
                    </div>

                    <div class="item">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service6.jpg'); ?>' ></a>
                      <h4>Nail Art</h4>
                      <h5>90.00 KD <span>120.00 KD</span></h5>
                    </div>





                  </div>
                  <!-- End Carousel Inner -->
                </div>
                <!-- /.carousel -->
                <li class="divider"></li>
                <li><a href="#">View all Collection </a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header"><a href="shop-by-category.html">Hair care</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li class="divider"></li>
                <li class="dropdown-header"><a href="shop-by-category.html">Skin Care</a></li>
                <li><a href="#">Skin Care Product 1</a></li>
                <li><a href="#">Skin Care Product 2</a></li>
								<li><a href="#">Skin Care Product 3</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header"><a href="shop-by-category.html">Nails care</a></li>
                <li><a href="#">Nails care Product</a></li>
                <li><a href="#">Nails care Product 1</a></li>
                <li><a href="#">Nails care Product 2</a></li>
                <li><a href="#">Nails care Product 3</a></li>
                <li><a href="#">Nails care Product 4</a></li>
                <li class="divider"></li>
                <li class="dropdown-header"><a href="shop-by-category.html">Accessories</a></li>
                <li><a href="#">Face Makeup</a></li>
                <li><a href="#">Coloring</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header"><a href="shop-by-category.html">Life Style</a></li>
                <li><a href="#">Massage</a></li>
                <li><a href="#">Eximia treatment</a></li>
                <li><a href="#">Micronized Agle Body </a></li>
                <li><a href="#">LPG treatment</a></li>
                <li><a href="#">Body Countouring</a></li>
                <li><a href="#">Art Of Beauty Slimming Treat</a></li>
                <!--<li class="divider"></li>-->
              </ul>
            </li>
          </ul>

        </li>
                    <li class="dropdown mega-dropdown">
          <a href="service.html" class="dropdown-toggle" data-toggle="dropdown">Services
          <span class="glyphicon glyphicon-chevron-down pull-right caret-small"></span></a>

          <ul class="dropdown-menu mega-dropdown-menu row">
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Special Services</li>
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">

                    <div class="item active">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service1.jpg'); ?>' ></a>
                      <h4>Hair Colouring</h4>
                      <h5>30.00 KD <span>45.00 KD</span></h5>
                    </div>

                    <div class="item">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service2.jpg'); ?>' ></a>
                      <h4>Makeup</h4>
                      <h5>55.00 KD <span>70.00 KD</span></h5>
                    </div>

                    <div class="item">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service3.jpg'); ?>' ></a>
                      <h4>Nail Art</h4>
                      <h5>90.00 KD <span>120.00 KD</span></h5>
                    </div>





                  </div>
                  <!-- End Carousel Inner -->
                </div>
                <!-- /.carousel -->
                <li class="divider"></li>
                <li><a href="#">View all Collection </a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Hair</li>
                <li><a href="#">Cut & Style</a></li>
                <li><a href="#">Treatments</a></li>
                <li><a href="#">Colouring</a></li>
                <li><a href="#">Highlights</a></li>
                <li><a href="#">Extensions</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Make up</li>
                <li><a href="#">Threading</a></li>
                <li><a href="#">Microblading</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Nails</li>
                <li><a href="#">Manicure & Pedicure</a></li>
                <li><a href="#">Nail Art</a></li>
                <li><a href="#">Nails by Kseniya</a></li>
                <li><a href="#">Nail Extensions</a></li>
                <li><a href="#">Spa for hands & foot</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Face</li>
                <li><a href="#">Face Makeup</a></li>
                <li><a href="#">Coloring</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Body</li>
                <li><a href="#">Massage</a></li>
                <li><a href="#">Eximia treatment</a></li>
                <li><a href="#">Micronized Agle Body </a></li>
                <li><a href="#">LPG treatment</a></li>
                <li><a href="#">Body Countouring</a></li>
                <li><a href="#">Art Of Beauty Slimming Treat</a></li>
                <!--<li class="divider"></li>-->
              </ul>
            </li>
          </ul>

        </li>
                  	
   
                  <li class="dropdown mega-dropdown">
          <a href="shop-by-category.html">Shop
          <span class="glyphicon glyphicon-chevron-down pull-right caret-small"></span></a>

          <ul class="dropdown-menu mega-dropdown-menu megaMenu-1 row">
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header">Special Products</li>
                <div id="myCarousel2" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">

                    <div class="item active">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service4.jpg'); ?>' ></a>
                      <h4>Hair Colouring</h4>
                      <h5>30.00 KD <span>45.00 KD</span></h5>
                    </div>

                    <div class="item">
                      <a href="#"><img src='<?php echo $this->getViewFileUrl('images/service5.jpg'); ?>' ></a>
                      <h4>Makeup</h4>
                      <h5>55.00 KD <span>70.00 KD</span></h5>
                    </div>

                    <div class="item">
                      <a href="#">
					  <img src='<?php echo $this->getViewFileUrl('images/service6.jpg'); ?>' ></a>
                      <h4>Nail Art</h4>
                      <h5>90.00 KD <span>120.00 KD</span></h5>
                    </div>





                  </div>
                  <!-- End Carousel Inner -->
                </div>
                <!-- /.carousel -->
                <li class="divider"></li>
                <li><a href="#">View all Collection </a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header"><a href="shop-by-category.html">Hair care</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li><a href="#">Hair care Products</a></li>
                <li class="divider"></li>
                <li class="dropdown-header"><a href="shop-by-category.html">Skin Care</a></li>
                <li><a href="#">Skin Care Product 1</a></li>
                <li><a href="#">Skin Care Product 2</a></li>
								<li><a href="#">Skin Care Product 3</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header"><a href="shop-by-category.html">Nails care</a></li>
                <li><a href="#">Nails care Product</a></li>
                <li><a href="#">Nails care Product 1</a></li>
                <li><a href="#">Nails care Product 2</a></li>
                <li><a href="#">Nails care Product 3</a></li>
                <li><a href="#">Nails care Product 4</a></li>
                <li class="divider"></li>
                <li class="dropdown-header"><a href="shop-by-category.html">Accessories</a></li>
                <li><a href="#">Face Makeup</a></li>
                <li><a href="#">Coloring</a></li>
              </ul>
            </li>
            <li class="col-sm-3">
              <ul>
                <li class="dropdown-header"><a href="shop-by-category.html">Life Style</a></li>
                <li><a href="#">Massage</a></li>
                <li><a href="#">Eximia treatment</a></li>
                <li><a href="#">Micronized Agle Body </a></li>
                <li><a href="#">LPG treatment</a></li>
                <li><a href="#">Body Countouring</a></li>
                <li><a href="#">Art Of Beauty Slimming Treat</a></li>
                <!--<li class="divider"></li>-->
              </ul>
            </li>
          </ul>

        </li>	
					<li><a href="offer.html">Offers</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="online-booking.html">Book an Appointment</a></li>
                    <li><a href="contact-us.html">Contact US</a></li>

      </ul>

    </div>
    <!-- /.nav-collapse -->
  </nav>
<!--
    <div class="search">

    <input name="" type="button" class="srch_btn">
    <input name="" type="text" placeholder="Search Here" class="srch_box"> 
    </div>

    </nav>-->
    <!--nav-->

	</article>
	
	<p id="back-top">
		<a href="#top" title="Back to Top"><span></span></a>
</p>

		

	